// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/test.proto

package com.test.proto;

public final class TestProto {
  private TestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TestItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TestItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 id = 1;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>optional int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>optional string media_id = 2;</code>
     * @return Whether the mediaId field is set.
     */
    boolean hasMediaId();
    /**
     * <code>optional string media_id = 2;</code>
     * @return The mediaId.
     */
    java.lang.String getMediaId();
    /**
     * <code>optional string media_id = 2;</code>
     * @return The bytes for mediaId.
     */
    com.google.protobuf.ByteString
        getMediaIdBytes();

    /**
     * <code>optional int32 time_length = 3;</code>
     * @return Whether the timeLength field is set.
     */
    boolean hasTimeLength();
    /**
     * <code>optional int32 time_length = 3;</code>
     * @return The timeLength.
     */
    int getTimeLength();
  }
  /**
   * Protobuf type {@code TestItem}
   */
  public  static final class TestItem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TestItem)
      TestItemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TestItem.newBuilder() to construct.
    private TestItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TestItem() {
      mediaId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TestItem();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TestItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              mediaId_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timeLength_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.test.proto.TestProto.internal_static_TestItem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.test.proto.TestProto.internal_static_TestItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.test.proto.TestProto.TestItem.class, com.test.proto.TestProto.TestItem.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional int64 id = 1;</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int64 id = 1;</code>
     * @return The id.
     */
    public long getId() {
      return id_;
    }

    public static final int MEDIA_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object mediaId_;
    /**
     * <code>optional string media_id = 2;</code>
     * @return Whether the mediaId field is set.
     */
    public boolean hasMediaId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string media_id = 2;</code>
     * @return The mediaId.
     */
    public java.lang.String getMediaId() {
      java.lang.Object ref = mediaId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mediaId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string media_id = 2;</code>
     * @return The bytes for mediaId.
     */
    public com.google.protobuf.ByteString
        getMediaIdBytes() {
      java.lang.Object ref = mediaId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mediaId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_LENGTH_FIELD_NUMBER = 3;
    private int timeLength_;
    /**
     * <code>optional int32 time_length = 3;</code>
     * @return Whether the timeLength field is set.
     */
    public boolean hasTimeLength() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 time_length = 3;</code>
     * @return The timeLength.
     */
    public int getTimeLength() {
      return timeLength_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, mediaId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, timeLength_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, mediaId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, timeLength_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.test.proto.TestProto.TestItem)) {
        return super.equals(obj);
      }
      com.test.proto.TestProto.TestItem other = (com.test.proto.TestProto.TestItem) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (getId()
            != other.getId()) return false;
      }
      if (hasMediaId() != other.hasMediaId()) return false;
      if (hasMediaId()) {
        if (!getMediaId()
            .equals(other.getMediaId())) return false;
      }
      if (hasTimeLength() != other.hasTimeLength()) return false;
      if (hasTimeLength()) {
        if (getTimeLength()
            != other.getTimeLength()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getId());
      }
      if (hasMediaId()) {
        hash = (37 * hash) + MEDIA_ID_FIELD_NUMBER;
        hash = (53 * hash) + getMediaId().hashCode();
      }
      if (hasTimeLength()) {
        hash = (37 * hash) + TIME_LENGTH_FIELD_NUMBER;
        hash = (53 * hash) + getTimeLength();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.test.proto.TestProto.TestItem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.TestProto.TestItem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.TestProto.TestItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.TestProto.TestItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.TestProto.TestItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.TestProto.TestItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.TestProto.TestItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.test.proto.TestProto.TestItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.test.proto.TestProto.TestItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.test.proto.TestProto.TestItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.test.proto.TestProto.TestItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.test.proto.TestProto.TestItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.test.proto.TestProto.TestItem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TestItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TestItem)
        com.test.proto.TestProto.TestItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.test.proto.TestProto.internal_static_TestItem_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.test.proto.TestProto.internal_static_TestItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.test.proto.TestProto.TestItem.class, com.test.proto.TestProto.TestItem.Builder.class);
      }

      // Construct using com.test.proto.TestProto.TestItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        mediaId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        timeLength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.test.proto.TestProto.internal_static_TestItem_descriptor;
      }

      @java.lang.Override
      public com.test.proto.TestProto.TestItem getDefaultInstanceForType() {
        return com.test.proto.TestProto.TestItem.getDefaultInstance();
      }

      @java.lang.Override
      public com.test.proto.TestProto.TestItem build() {
        com.test.proto.TestProto.TestItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.test.proto.TestProto.TestItem buildPartial() {
        com.test.proto.TestProto.TestItem result = new com.test.proto.TestProto.TestItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.mediaId_ = mediaId_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.timeLength_ = timeLength_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.test.proto.TestProto.TestItem) {
          return mergeFrom((com.test.proto.TestProto.TestItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.test.proto.TestProto.TestItem other) {
        if (other == com.test.proto.TestProto.TestItem.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasMediaId()) {
          bitField0_ |= 0x00000002;
          mediaId_ = other.mediaId_;
          onChanged();
        }
        if (other.hasTimeLength()) {
          setTimeLength(other.getTimeLength());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.test.proto.TestProto.TestItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.test.proto.TestProto.TestItem) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>optional int64 id = 1;</code>
       * @return Whether the id field is set.
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int64 id = 1;</code>
       * @return The id.
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object mediaId_ = "";
      /**
       * <code>optional string media_id = 2;</code>
       * @return Whether the mediaId field is set.
       */
      public boolean hasMediaId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string media_id = 2;</code>
       * @return The mediaId.
       */
      public java.lang.String getMediaId() {
        java.lang.Object ref = mediaId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mediaId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string media_id = 2;</code>
       * @return The bytes for mediaId.
       */
      public com.google.protobuf.ByteString
          getMediaIdBytes() {
        java.lang.Object ref = mediaId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mediaId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string media_id = 2;</code>
       * @param value The mediaId to set.
       * @return This builder for chaining.
       */
      public Builder setMediaId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        mediaId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string media_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMediaId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        mediaId_ = getDefaultInstance().getMediaId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string media_id = 2;</code>
       * @param value The bytes for mediaId to set.
       * @return This builder for chaining.
       */
      public Builder setMediaIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        mediaId_ = value;
        onChanged();
        return this;
      }

      private int timeLength_ ;
      /**
       * <code>optional int32 time_length = 3;</code>
       * @return Whether the timeLength field is set.
       */
      public boolean hasTimeLength() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 time_length = 3;</code>
       * @return The timeLength.
       */
      public int getTimeLength() {
        return timeLength_;
      }
      /**
       * <code>optional int32 time_length = 3;</code>
       * @param value The timeLength to set.
       * @return This builder for chaining.
       */
      public Builder setTimeLength(int value) {
        bitField0_ |= 0x00000004;
        timeLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 time_length = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimeLength() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timeLength_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TestItem)
    }

    // @@protoc_insertion_point(class_scope:TestItem)
    private static final com.test.proto.TestProto.TestItem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.test.proto.TestProto.TestItem();
    }

    public static com.test.proto.TestProto.TestItem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TestItem>
        PARSER = new com.google.protobuf.AbstractParser<TestItem>() {
      @java.lang.Override
      public TestItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestItem(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TestItem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TestItem> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.test.proto.TestProto.TestItem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TestItemResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TestItemResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .BaseResponse response = 1;</code>
     * @return Whether the response field is set.
     */
    boolean hasResponse();
    /**
     * <code>optional .BaseResponse response = 1;</code>
     * @return The response.
     */
    com.test.proto.base.RespProto.BaseResponse getResponse();
    /**
     * <code>optional .BaseResponse response = 1;</code>
     */
    com.test.proto.base.RespProto.BaseResponseOrBuilder getResponseOrBuilder();

    /**
     * <code>repeated .TestItem audio_items = 2;</code>
     */
    java.util.List<com.test.proto.TestProto.TestItem> 
        getAudioItemsList();
    /**
     * <code>repeated .TestItem audio_items = 2;</code>
     */
    com.test.proto.TestProto.TestItem getAudioItems(int index);
    /**
     * <code>repeated .TestItem audio_items = 2;</code>
     */
    int getAudioItemsCount();
    /**
     * <code>repeated .TestItem audio_items = 2;</code>
     */
    java.util.List<? extends com.test.proto.TestProto.TestItemOrBuilder> 
        getAudioItemsOrBuilderList();
    /**
     * <code>repeated .TestItem audio_items = 2;</code>
     */
    com.test.proto.TestProto.TestItemOrBuilder getAudioItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code TestItemResponse}
   */
  public  static final class TestItemResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TestItemResponse)
      TestItemResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TestItemResponse.newBuilder() to construct.
    private TestItemResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TestItemResponse() {
      audioItems_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TestItemResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TestItemResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.test.proto.base.RespProto.BaseResponse.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = response_.toBuilder();
              }
              response_ = input.readMessage(com.test.proto.base.RespProto.BaseResponse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(response_);
                response_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                audioItems_ = new java.util.ArrayList<com.test.proto.TestProto.TestItem>();
                mutable_bitField0_ |= 0x00000002;
              }
              audioItems_.add(
                  input.readMessage(com.test.proto.TestProto.TestItem.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          audioItems_ = java.util.Collections.unmodifiableList(audioItems_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.test.proto.TestProto.internal_static_TestItemResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.test.proto.TestProto.internal_static_TestItemResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.test.proto.TestProto.TestItemResponse.class, com.test.proto.TestProto.TestItemResponse.Builder.class);
    }

    private int bitField0_;
    public static final int RESPONSE_FIELD_NUMBER = 1;
    private com.test.proto.base.RespProto.BaseResponse response_;
    /**
     * <code>optional .BaseResponse response = 1;</code>
     * @return Whether the response field is set.
     */
    public boolean hasResponse() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .BaseResponse response = 1;</code>
     * @return The response.
     */
    public com.test.proto.base.RespProto.BaseResponse getResponse() {
      return response_ == null ? com.test.proto.base.RespProto.BaseResponse.getDefaultInstance() : response_;
    }
    /**
     * <code>optional .BaseResponse response = 1;</code>
     */
    public com.test.proto.base.RespProto.BaseResponseOrBuilder getResponseOrBuilder() {
      return response_ == null ? com.test.proto.base.RespProto.BaseResponse.getDefaultInstance() : response_;
    }

    public static final int AUDIO_ITEMS_FIELD_NUMBER = 2;
    private java.util.List<com.test.proto.TestProto.TestItem> audioItems_;
    /**
     * <code>repeated .TestItem audio_items = 2;</code>
     */
    public java.util.List<com.test.proto.TestProto.TestItem> getAudioItemsList() {
      return audioItems_;
    }
    /**
     * <code>repeated .TestItem audio_items = 2;</code>
     */
    public java.util.List<? extends com.test.proto.TestProto.TestItemOrBuilder> 
        getAudioItemsOrBuilderList() {
      return audioItems_;
    }
    /**
     * <code>repeated .TestItem audio_items = 2;</code>
     */
    public int getAudioItemsCount() {
      return audioItems_.size();
    }
    /**
     * <code>repeated .TestItem audio_items = 2;</code>
     */
    public com.test.proto.TestProto.TestItem getAudioItems(int index) {
      return audioItems_.get(index);
    }
    /**
     * <code>repeated .TestItem audio_items = 2;</code>
     */
    public com.test.proto.TestProto.TestItemOrBuilder getAudioItemsOrBuilder(
        int index) {
      return audioItems_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getResponse());
      }
      for (int i = 0; i < audioItems_.size(); i++) {
        output.writeMessage(2, audioItems_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getResponse());
      }
      for (int i = 0; i < audioItems_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, audioItems_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.test.proto.TestProto.TestItemResponse)) {
        return super.equals(obj);
      }
      com.test.proto.TestProto.TestItemResponse other = (com.test.proto.TestProto.TestItemResponse) obj;

      if (hasResponse() != other.hasResponse()) return false;
      if (hasResponse()) {
        if (!getResponse()
            .equals(other.getResponse())) return false;
      }
      if (!getAudioItemsList()
          .equals(other.getAudioItemsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasResponse()) {
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
      }
      if (getAudioItemsCount() > 0) {
        hash = (37 * hash) + AUDIO_ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getAudioItemsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.test.proto.TestProto.TestItemResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.TestProto.TestItemResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.TestProto.TestItemResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.TestProto.TestItemResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.TestProto.TestItemResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.TestProto.TestItemResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.TestProto.TestItemResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.test.proto.TestProto.TestItemResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.test.proto.TestProto.TestItemResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.test.proto.TestProto.TestItemResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.test.proto.TestProto.TestItemResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.test.proto.TestProto.TestItemResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.test.proto.TestProto.TestItemResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TestItemResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TestItemResponse)
        com.test.proto.TestProto.TestItemResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.test.proto.TestProto.internal_static_TestItemResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.test.proto.TestProto.internal_static_TestItemResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.test.proto.TestProto.TestItemResponse.class, com.test.proto.TestProto.TestItemResponse.Builder.class);
      }

      // Construct using com.test.proto.TestProto.TestItemResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getResponseFieldBuilder();
          getAudioItemsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (responseBuilder_ == null) {
          response_ = null;
        } else {
          responseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (audioItemsBuilder_ == null) {
          audioItems_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          audioItemsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.test.proto.TestProto.internal_static_TestItemResponse_descriptor;
      }

      @java.lang.Override
      public com.test.proto.TestProto.TestItemResponse getDefaultInstanceForType() {
        return com.test.proto.TestProto.TestItemResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.test.proto.TestProto.TestItemResponse build() {
        com.test.proto.TestProto.TestItemResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.test.proto.TestProto.TestItemResponse buildPartial() {
        com.test.proto.TestProto.TestItemResponse result = new com.test.proto.TestProto.TestItemResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (responseBuilder_ == null) {
            result.response_ = response_;
          } else {
            result.response_ = responseBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        if (audioItemsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            audioItems_ = java.util.Collections.unmodifiableList(audioItems_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.audioItems_ = audioItems_;
        } else {
          result.audioItems_ = audioItemsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.test.proto.TestProto.TestItemResponse) {
          return mergeFrom((com.test.proto.TestProto.TestItemResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.test.proto.TestProto.TestItemResponse other) {
        if (other == com.test.proto.TestProto.TestItemResponse.getDefaultInstance()) return this;
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        if (audioItemsBuilder_ == null) {
          if (!other.audioItems_.isEmpty()) {
            if (audioItems_.isEmpty()) {
              audioItems_ = other.audioItems_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureAudioItemsIsMutable();
              audioItems_.addAll(other.audioItems_);
            }
            onChanged();
          }
        } else {
          if (!other.audioItems_.isEmpty()) {
            if (audioItemsBuilder_.isEmpty()) {
              audioItemsBuilder_.dispose();
              audioItemsBuilder_ = null;
              audioItems_ = other.audioItems_;
              bitField0_ = (bitField0_ & ~0x00000002);
              audioItemsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAudioItemsFieldBuilder() : null;
            } else {
              audioItemsBuilder_.addAllMessages(other.audioItems_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.test.proto.TestProto.TestItemResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.test.proto.TestProto.TestItemResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.test.proto.base.RespProto.BaseResponse response_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.test.proto.base.RespProto.BaseResponse, com.test.proto.base.RespProto.BaseResponse.Builder, com.test.proto.base.RespProto.BaseResponseOrBuilder> responseBuilder_;
      /**
       * <code>optional .BaseResponse response = 1;</code>
       * @return Whether the response field is set.
       */
      public boolean hasResponse() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .BaseResponse response = 1;</code>
       * @return The response.
       */
      public com.test.proto.base.RespProto.BaseResponse getResponse() {
        if (responseBuilder_ == null) {
          return response_ == null ? com.test.proto.base.RespProto.BaseResponse.getDefaultInstance() : response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .BaseResponse response = 1;</code>
       */
      public Builder setResponse(com.test.proto.base.RespProto.BaseResponse value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .BaseResponse response = 1;</code>
       */
      public Builder setResponse(
          com.test.proto.base.RespProto.BaseResponse.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .BaseResponse response = 1;</code>
       */
      public Builder mergeResponse(com.test.proto.base.RespProto.BaseResponse value) {
        if (responseBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              response_ != null &&
              response_ != com.test.proto.base.RespProto.BaseResponse.getDefaultInstance()) {
            response_ =
              com.test.proto.base.RespProto.BaseResponse.newBuilder(response_).mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          responseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .BaseResponse response = 1;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          response_ = null;
          onChanged();
        } else {
          responseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .BaseResponse response = 1;</code>
       */
      public com.test.proto.base.RespProto.BaseResponse.Builder getResponseBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .BaseResponse response = 1;</code>
       */
      public com.test.proto.base.RespProto.BaseResponseOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_ == null ?
              com.test.proto.base.RespProto.BaseResponse.getDefaultInstance() : response_;
        }
      }
      /**
       * <code>optional .BaseResponse response = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.test.proto.base.RespProto.BaseResponse, com.test.proto.base.RespProto.BaseResponse.Builder, com.test.proto.base.RespProto.BaseResponseOrBuilder> 
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.test.proto.base.RespProto.BaseResponse, com.test.proto.base.RespProto.BaseResponse.Builder, com.test.proto.base.RespProto.BaseResponseOrBuilder>(
                  getResponse(),
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }

      private java.util.List<com.test.proto.TestProto.TestItem> audioItems_ =
        java.util.Collections.emptyList();
      private void ensureAudioItemsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          audioItems_ = new java.util.ArrayList<com.test.proto.TestProto.TestItem>(audioItems_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.test.proto.TestProto.TestItem, com.test.proto.TestProto.TestItem.Builder, com.test.proto.TestProto.TestItemOrBuilder> audioItemsBuilder_;

      /**
       * <code>repeated .TestItem audio_items = 2;</code>
       */
      public java.util.List<com.test.proto.TestProto.TestItem> getAudioItemsList() {
        if (audioItemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(audioItems_);
        } else {
          return audioItemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .TestItem audio_items = 2;</code>
       */
      public int getAudioItemsCount() {
        if (audioItemsBuilder_ == null) {
          return audioItems_.size();
        } else {
          return audioItemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .TestItem audio_items = 2;</code>
       */
      public com.test.proto.TestProto.TestItem getAudioItems(int index) {
        if (audioItemsBuilder_ == null) {
          return audioItems_.get(index);
        } else {
          return audioItemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .TestItem audio_items = 2;</code>
       */
      public Builder setAudioItems(
          int index, com.test.proto.TestProto.TestItem value) {
        if (audioItemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAudioItemsIsMutable();
          audioItems_.set(index, value);
          onChanged();
        } else {
          audioItemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TestItem audio_items = 2;</code>
       */
      public Builder setAudioItems(
          int index, com.test.proto.TestProto.TestItem.Builder builderForValue) {
        if (audioItemsBuilder_ == null) {
          ensureAudioItemsIsMutable();
          audioItems_.set(index, builderForValue.build());
          onChanged();
        } else {
          audioItemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TestItem audio_items = 2;</code>
       */
      public Builder addAudioItems(com.test.proto.TestProto.TestItem value) {
        if (audioItemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAudioItemsIsMutable();
          audioItems_.add(value);
          onChanged();
        } else {
          audioItemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .TestItem audio_items = 2;</code>
       */
      public Builder addAudioItems(
          int index, com.test.proto.TestProto.TestItem value) {
        if (audioItemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAudioItemsIsMutable();
          audioItems_.add(index, value);
          onChanged();
        } else {
          audioItemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TestItem audio_items = 2;</code>
       */
      public Builder addAudioItems(
          com.test.proto.TestProto.TestItem.Builder builderForValue) {
        if (audioItemsBuilder_ == null) {
          ensureAudioItemsIsMutable();
          audioItems_.add(builderForValue.build());
          onChanged();
        } else {
          audioItemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TestItem audio_items = 2;</code>
       */
      public Builder addAudioItems(
          int index, com.test.proto.TestProto.TestItem.Builder builderForValue) {
        if (audioItemsBuilder_ == null) {
          ensureAudioItemsIsMutable();
          audioItems_.add(index, builderForValue.build());
          onChanged();
        } else {
          audioItemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TestItem audio_items = 2;</code>
       */
      public Builder addAllAudioItems(
          java.lang.Iterable<? extends com.test.proto.TestProto.TestItem> values) {
        if (audioItemsBuilder_ == null) {
          ensureAudioItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, audioItems_);
          onChanged();
        } else {
          audioItemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .TestItem audio_items = 2;</code>
       */
      public Builder clearAudioItems() {
        if (audioItemsBuilder_ == null) {
          audioItems_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          audioItemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .TestItem audio_items = 2;</code>
       */
      public Builder removeAudioItems(int index) {
        if (audioItemsBuilder_ == null) {
          ensureAudioItemsIsMutable();
          audioItems_.remove(index);
          onChanged();
        } else {
          audioItemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .TestItem audio_items = 2;</code>
       */
      public com.test.proto.TestProto.TestItem.Builder getAudioItemsBuilder(
          int index) {
        return getAudioItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .TestItem audio_items = 2;</code>
       */
      public com.test.proto.TestProto.TestItemOrBuilder getAudioItemsOrBuilder(
          int index) {
        if (audioItemsBuilder_ == null) {
          return audioItems_.get(index);  } else {
          return audioItemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .TestItem audio_items = 2;</code>
       */
      public java.util.List<? extends com.test.proto.TestProto.TestItemOrBuilder> 
           getAudioItemsOrBuilderList() {
        if (audioItemsBuilder_ != null) {
          return audioItemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(audioItems_);
        }
      }
      /**
       * <code>repeated .TestItem audio_items = 2;</code>
       */
      public com.test.proto.TestProto.TestItem.Builder addAudioItemsBuilder() {
        return getAudioItemsFieldBuilder().addBuilder(
            com.test.proto.TestProto.TestItem.getDefaultInstance());
      }
      /**
       * <code>repeated .TestItem audio_items = 2;</code>
       */
      public com.test.proto.TestProto.TestItem.Builder addAudioItemsBuilder(
          int index) {
        return getAudioItemsFieldBuilder().addBuilder(
            index, com.test.proto.TestProto.TestItem.getDefaultInstance());
      }
      /**
       * <code>repeated .TestItem audio_items = 2;</code>
       */
      public java.util.List<com.test.proto.TestProto.TestItem.Builder> 
           getAudioItemsBuilderList() {
        return getAudioItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.test.proto.TestProto.TestItem, com.test.proto.TestProto.TestItem.Builder, com.test.proto.TestProto.TestItemOrBuilder> 
          getAudioItemsFieldBuilder() {
        if (audioItemsBuilder_ == null) {
          audioItemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.test.proto.TestProto.TestItem, com.test.proto.TestProto.TestItem.Builder, com.test.proto.TestProto.TestItemOrBuilder>(
                  audioItems_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          audioItems_ = null;
        }
        return audioItemsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TestItemResponse)
    }

    // @@protoc_insertion_point(class_scope:TestItemResponse)
    private static final com.test.proto.TestProto.TestItemResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.test.proto.TestProto.TestItemResponse();
    }

    public static com.test.proto.TestProto.TestItemResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TestItemResponse>
        PARSER = new com.google.protobuf.AbstractParser<TestItemResponse>() {
      @java.lang.Override
      public TestItemResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestItemResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TestItemResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TestItemResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.test.proto.TestProto.TestItemResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TestItem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TestItem_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TestItemResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TestItemResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017user/test.proto\032\017base/resp.proto\"=\n\010Te" +
      "stItem\022\n\n\002id\030\001 \001(\003\022\020\n\010media_id\030\002 \001(\t\022\023\n\013" +
      "time_length\030\003 \001(\005\"S\n\020TestItemResponse\022\037\n" +
      "\010response\030\001 \001(\0132\r.BaseResponse\022\036\n\013audio_" +
      "items\030\002 \003(\0132\t.TestItemB!\n\016com.test.proto" +
      "B\tTestProto\242\002\003GPB"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.test.proto.base.RespProto.getDescriptor(),
        });
    internal_static_TestItem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TestItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TestItem_descriptor,
        new java.lang.String[] { "Id", "MediaId", "TimeLength", });
    internal_static_TestItemResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TestItemResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TestItemResponse_descriptor,
        new java.lang.String[] { "Response", "AudioItems", });
    com.test.proto.base.RespProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
