// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ignore_two/ignore_test_two.proto

package com.test.proto.ignoreTwo;

public final class IgnoreTestTwoProto {
  private IgnoreTestTwoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface IgnoreTwoTestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IgnoreTwoTest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>optional string media_id = 2;</code>
     */
    boolean hasMediaId();
    /**
     * <code>optional string media_id = 2;</code>
     */
    java.lang.String getMediaId();
    /**
     * <code>optional string media_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getMediaIdBytes();

    /**
     * <code>optional int32 time_length = 3;</code>
     */
    boolean hasTimeLength();
    /**
     * <code>optional int32 time_length = 3;</code>
     */
    int getTimeLength();
  }
  /**
   * Protobuf type {@code IgnoreTwoTest}
   */
  public  static final class IgnoreTwoTest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:IgnoreTwoTest)
      IgnoreTwoTestOrBuilder {
    // Use IgnoreTwoTest.newBuilder() to construct.
    private IgnoreTwoTest(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private IgnoreTwoTest() {
      id_ = 0L;
      mediaId_ = "";
      timeLength_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IgnoreTwoTest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              mediaId_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timeLength_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.test.proto.ignoreTwo.IgnoreTestTwoProto.internal_static_IgnoreTwoTest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.test.proto.ignoreTwo.IgnoreTestTwoProto.internal_static_IgnoreTwoTest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTest.class, com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTest.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int MEDIA_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object mediaId_;
    /**
     * <code>optional string media_id = 2;</code>
     */
    public boolean hasMediaId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string media_id = 2;</code>
     */
    public java.lang.String getMediaId() {
      java.lang.Object ref = mediaId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mediaId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string media_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMediaIdBytes() {
      java.lang.Object ref = mediaId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mediaId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_LENGTH_FIELD_NUMBER = 3;
    private int timeLength_;
    /**
     * <code>optional int32 time_length = 3;</code>
     */
    public boolean hasTimeLength() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 time_length = 3;</code>
     */
    public int getTimeLength() {
      return timeLength_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMediaIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, timeLength_);
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMediaIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, timeLength_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code IgnoreTwoTest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:IgnoreTwoTest)
        com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.test.proto.ignoreTwo.IgnoreTestTwoProto.internal_static_IgnoreTwoTest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.test.proto.ignoreTwo.IgnoreTestTwoProto.internal_static_IgnoreTwoTest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTest.class, com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTest.Builder.class);
      }

      // Construct using com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        mediaId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        timeLength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.test.proto.ignoreTwo.IgnoreTestTwoProto.internal_static_IgnoreTwoTest_descriptor;
      }

      public com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTest getDefaultInstanceForType() {
        return com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTest.getDefaultInstance();
      }

      public com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTest build() {
        com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTest buildPartial() {
        com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTest result = new com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.mediaId_ = mediaId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timeLength_ = timeLength_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTest) {
          return mergeFrom((com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTest other) {
        if (other == com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTest.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasMediaId()) {
          bitField0_ |= 0x00000002;
          mediaId_ = other.mediaId_;
          onChanged();
        }
        if (other.hasTimeLength()) {
          setTimeLength(other.getTimeLength());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>optional int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object mediaId_ = "";
      /**
       * <code>optional string media_id = 2;</code>
       */
      public boolean hasMediaId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string media_id = 2;</code>
       */
      public java.lang.String getMediaId() {
        java.lang.Object ref = mediaId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mediaId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string media_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMediaIdBytes() {
        java.lang.Object ref = mediaId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mediaId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string media_id = 2;</code>
       */
      public Builder setMediaId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        mediaId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string media_id = 2;</code>
       */
      public Builder clearMediaId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        mediaId_ = getDefaultInstance().getMediaId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string media_id = 2;</code>
       */
      public Builder setMediaIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        mediaId_ = value;
        onChanged();
        return this;
      }

      private int timeLength_ ;
      /**
       * <code>optional int32 time_length = 3;</code>
       */
      public boolean hasTimeLength() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 time_length = 3;</code>
       */
      public int getTimeLength() {
        return timeLength_;
      }
      /**
       * <code>optional int32 time_length = 3;</code>
       */
      public Builder setTimeLength(int value) {
        bitField0_ |= 0x00000004;
        timeLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 time_length = 3;</code>
       */
      public Builder clearTimeLength() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timeLength_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IgnoreTwoTest)
    }

    // @@protoc_insertion_point(class_scope:IgnoreTwoTest)
    private static final com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTest();
    }

    public static com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<IgnoreTwoTest> PARSER =
        new com.google.protobuf.AbstractParser<IgnoreTwoTest>() {
      public IgnoreTwoTest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new IgnoreTwoTest(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<IgnoreTwoTest> getParserForType() {
      return PARSER;
    }

    public com.test.proto.ignoreTwo.IgnoreTestTwoProto.IgnoreTwoTest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_IgnoreTwoTest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_IgnoreTwoTest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n ignore_two/ignore_test_two.proto\"B\n\rIg" +
      "noreTwoTest\022\n\n\002id\030\001 \001(\003\022\020\n\010media_id\030\002 \001(" +
      "\t\022\023\n\013time_length\030\003 \001(\005B4\n\030com.test.proto" +
      ".ignoreTwoB\022IgnoreTestTwoProto\242\002\003GPB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_IgnoreTwoTest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_IgnoreTwoTest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_IgnoreTwoTest_descriptor,
        new java.lang.String[] { "Id", "MediaId", "TimeLength", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
